In [1]:
from arch import arch_model
import numpy as np
import pandas as pd
i

In [4]:
df = pd.read_csv('전체기간.csv',index_col = 0)
df.head()

코스피       코스닥       SK㈜      롯데쇼핑      HD현대     서부티앤디  \
Date                                                                     
2022-04-04  0.006588  0.007176  0.024845  0.014359  0.012963  0.004854   
2022-04-05  0.000471  0.005436  0.000000 -0.002022  0.009141  0.028986   
2022-04-06 -0.008760 -0.009806  0.004040 -0.010132 -0.005435 -0.023474   
2022-04-07 -0.014322 -0.016095 -0.010060 -0.021494 -0.007286  0.000000   
2022-04-08  0.001680  0.007306  0.008130 -0.011506  0.005505  0.004808   

              하나금융지주      SK리츠      롯데리츠  코람코라이프인프라리츠  신한서부티앤디리츠   코람코더원리츠  
Date                                                                        
2022-04-04  0.002066  0.006211 -0.005172     0.007764   0.009690  0.024263  
2022-04-05 -0.028866 -0.001543 -0.010399     0.009245  -0.003839  0.037225  
2022-04-06  0.007431 -0.010819 -0.012259     0.009160   0.015414  0.019576  
2022-04-07 -0.015806  0.006250  0.003546     0.019667  -0.001898 -0.011200  
2022-04-08 -0.007495  0.010870  0.014134     0.008902   0.020913  0.001618

In [15]:
df1 = df['SK㈜'] * 100
df2 = df['SK리츠'] * 100

In [37]:
data = pd.concat([df1,df2], axis = 1)

In [38]:
data

SK㈜      SK리츠
Date                          
2022-04-04  2.484471  0.621119
2022-04-05  0.000000 -0.154306
2022-04-06  0.404043 -1.081924
2022-04-07 -1.006032  0.624992
2022-04-08  0.812999  1.086955
...              ...       ...
2024-03-25 -1.725943  1.696970
2024-03-26  0.266102 -0.595948
2024-03-27 -1.698518 -0.599520
2024-03-28 -1.403883 -1.326900
2024-03-29 -0.279174  0.244499

[490 rows x 2 columns]

In [39]:
import pandas as pd
import numpy as np
from statsmodels.tsa.api import VAR
from statsmodels.tsa.stattools import adfuller

# 예시 데이터 생성
np.random.seed(0)


# 차분이 필요한 경우 수행
data_diff = data.diff().dropna()

# VAR 모델 학습 (차분된 데이터를 사용)
model = VAR(data_diff)

# 모델 적합
results = model.fit(maxlags=15, ic='aic')

# # 모델 요약 정보 출력
print(results.summary())

  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Fri, 19, Apr, 2024
Time:                     11:30:53
--------------------------------------------------------------------
No. of Equations:         2.00000    BIC:                    2.85183
Nobs:                     474.000    HQIC:                   2.52160
Log likelihood:          -1830.04    FPE:                    10.0534
AIC:                      2.30753    Det(Omega_mle):         8.85698
--------------------------------------------------------------------
Results for equation SK㈜
              coefficient       std. error           t-stat            prob
---------------------------------------------------------------------------
const           -0.010690         0.092768           -0.115           0.908
L1.SK㈜          -0.891219         0.048261          -18.467           0.000
L1.SK리츠         -0.009010         0.064310           -0.140           0.889
L2.SK㈜

C:\Users\geonh\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)


In [42]:
print(results.test_causality('SK리츠', ['SK㈜'], kind='f'))

<statsmodels.tsa.vector_ar.hypothesis_test_results.CausalityTestResults object. H_0: SK㈜ does not Granger-cause SK리츠: reject at 5% significance level. Test statistic: 1.716, critical value: 1.678>, p-value: 0.043>


In [44]:
data = pd.concat([df['롯데쇼핑'],df['롯데리츠']], axis = 1)


롯데쇼핑      롯데리츠
Date                          
2022-04-04  0.014359 -0.005172
2022-04-05 -0.002022 -0.010399
2022-04-06 -0.010132 -0.012259
2022-04-07 -0.021494  0.003546
2022-04-08 -0.011506  0.014134
...              ...       ...
2024-03-25 -0.017520  0.000000
2024-03-26  0.012346  0.000000
2024-03-27 -0.004065 -0.010606
2024-03-28  0.001361 -0.006126
2024-03-29 -0.019022 -0.004622

[490 rows x 2 columns]

In [46]:
data_diff = data.diff().dropna()

# VAR 모델 학습 (차분된 데이터를 사용)
model = VAR(data_diff)

# 모델 적합
results = model.fit(maxlags=15, ic='aic')

# # 모델 요약 정보 출력
print(results.summary())

print(results.test_causality('롯데쇼핑', ['롯데리츠'], kind='f'))

  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Fri, 19, Apr, 2024
Time:                     11:33:49
--------------------------------------------------------------------
No. of Equations:         2.00000    BIC:                   -16.2793
Nobs:                     480.000    HQIC:                  -16.4798
Log likelihood:           2662.14    FPE:                6.11704e-08
AIC:                     -16.6097    Det(Omega_mle):     5.66008e-08
--------------------------------------------------------------------
Results for equation 롯데쇼핑
             coefficient       std. error           t-stat            prob
--------------------------------------------------------------------------
const           0.000006         0.000895            0.006           0.995
L1.롯데쇼핑        -0.985106         0.047164          -20.887           0.000
L1.롯데리츠        -0.013453         0.074313           -0.181           0.856
L2.롯데쇼핑   

C:\Users\geonh\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\tsa\base\tsa_model.py:473: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  self._init_dates(dates, freq)


In [54]:
from statsmodels.tsa.stattools import grangercausalitytests
test_result = grangercausalitytests(data, 5, verbose=True)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0493  , p=0.8244  , df_denom=486, df_num=1
ssr based chi2 test:   chi2=0.0496  , p=0.8238  , df=1
likelihood ratio test: chi2=0.0496  , p=0.8238  , df=1
parameter F test:         F=0.0493  , p=0.8244  , df_denom=486, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0921  , p=0.9120  , df_denom=483, df_num=2
ssr based chi2 test:   chi2=0.1862  , p=0.9111  , df=2
likelihood ratio test: chi2=0.1862  , p=0.9111  , df=2
parameter F test:         F=0.0921  , p=0.9120  , df_denom=483, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.0328  , p=0.9920  , df_denom=480, df_num=3
ssr based chi2 test:   chi2=0.0999  , p=0.9919  , df=3
likelihood ratio test: chi2=0.0999  , p=0.9919  , df=3
parameter F test:         F=0.0328  , p=0.9920  , df_denom=480, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.0423  , p=0.9966  

In [55]:
test_result

{1: ({'ssr_ftest': (0.04926057309289258, 0.8244481945404086, 486.0, 1),
   'ssr_chi2test': (0.0495646507045771, 0.8238225526052427, 1),
   'lrtest': (0.049562138957298885, 0.8238269433978966, 1),
   'params_ftest': (0.04926057309277206, 0.8244481945405978, 486.0, 1.0)},
   array([[0., 1., 0.]])]),
 2: ({'ssr_ftest': (0.092143286499693, 0.9119904937039528, 483.0, 2),
   'ssr_chi2test': (0.18619430149834446, 0.9111049814648509, 2),
   'lrtest': (0.18615878971354505, 0.9111211590904903, 2),
   'params_ftest': (0.09214328649974753, 0.9119904937039038, 483.0, 2.0)},
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 3: ({'ssr_ftest': (0.03281637310024987, 0.9920118762176048, 480.0, 3),
   'ssr_chi2test': (0.09988483562388552, 0.9918512403235669, 3),
   'lrtest': (0.09987459371814111, 0.9918524687266069, 3),
   'params_ftest': (0.03281637310019294, 0.9920118762176239, 480.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0.

In [2]:
data

NameError: name 'data' is not defined